package proxy

import (
	"crypto/tls"
	"net/http"
	"sync"
	"time"
)

// Protocol identifies the application-layer protocol of an exchange.
type Protocol string

const (
	ProtoHTTP1  Protocol = "HTTP/1.1"
	ProtoHTTP2  Protocol = "HTTP/2"
	ProtoWS     Protocol = "WebSocket"
	ProtoTunnel Protocol = "TUNNEL" // opaque CONNECT tunnel (non-intercepted)
)

// TLSInfo holds metadata about the TLS session for an exchange.
type TLSInfo struct {
	// Version is the negotiated TLS version (tls.VersionTLS13 etc.)
	Version uint16
	// CipherSuite is the negotiated cipher suite ID.
	CipherSuite uint16
	// ServerName is the SNI hostname sent by the client.
	ServerName string
	// ALPN is the negotiated application protocol ("h2", "http/1.1", …).
	ALPN string
	// ForgedCert is the leaf certificate generated by mitm for this host.
	ForgedCert []byte // DER
	// UpstreamCert is the real certificate presented by the upstream server.
	UpstreamCert []byte // DER
}

// Timing records the precise timestamps for each phase of an exchange.
type Timing struct {
	Start        time.Time
	DNSResolved  time.Time
	TCPConnected time.Time
	TLSHandshook time.Time
	RequestSent  time.Time
	FirstByte    time.Time
	Done         time.Time
}

// Duration returns the total wall-clock duration of the exchange.
func (t Timing) Duration() time.Duration {
	if t.Done.IsZero() {
		return time.Since(t.Start)
	}
	return t.Done.Sub(t.Start)
}

// Exchange is the core unit of observation: one request + its response.
// It is written by the proxy layer and read by the store, the bus, and the GUI.
type Exchange struct {
	// ID is a monotonically increasing sequence number, unique per session.
	ID uint64
	// UUID is a stable identifier that survives session restarts (e.g. for replay).
	UUID string

	Protocol Protocol
	TLS      *TLSInfo // nil for plain HTTP

	Request  *http.Request
	Response *http.Response

	// ReqBody and RespBody hold the full decoded (decompressed) bodies.
	// The original http.Request/Response bodies are drained and replaced with
	// bytes.NewReader wrappers pointing at these slices.
	ReqBody  []byte
	RespBody []byte

	// RawReqBytes is the wire representation of the request (for replay / hex view).
	RawReqBytes []byte

	Timing Timing
	Error  error // set if the exchange did not complete normally

	mu    sync.Mutex
	tags  []string
	notes string
}

// Tag adds a free-form label to the exchange (e.g. "modified", "replayed").
func (e *Exchange) Tag(t string) {
	e.mu.Lock()
	e.tags = append(e.tags, t)
	e.mu.Unlock()
}

// Tags returns a snapshot of the exchange's labels.
func (e *Exchange) Tags() []string {
	e.mu.Lock()
	defer e.mu.Unlock()
	out := make([]string, len(e.tags))
	copy(out, e.tags)
	return out
}

// TLSVersionString returns a human-readable TLS version string.
func TLSVersionString(v uint16) string {
	switch v {
	case tls.VersionTLS10:
		return "TLS 1.0"
	case tls.VersionTLS11:
		return "TLS 1.1"
	case tls.VersionTLS12:
		return "TLS 1.2"
	case tls.VersionTLS13:
		return "TLS 1.3"
	default:
		return "unknown"
	}
}
